name: 'Swift Macro Compatibility Check'
description: 'Builds and optionally tests a Swift package with macros using all relevant swift-syntax versions'
inputs:
  run-tests:
    description: 'Whether to run tests (true/false)'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Check Swift package compatibility
      shell: bash
      run: |
        # List of all relevant swift-syntax versions to test against
        VERSIONS=("508.0.0" "509.0.0" "510.0.0" "511.0.0")
        
        for version in "${VERSIONS[@]}"; do
          echo "Testing compatibility with swift-syntax version $version"
          
          # Resolve dependencies
          swift package resolve
          swift package resolve swift-syntax --version $version
          
          echo "Building package with swift-syntax $version"
          if swift build -v; then
            echo "Build succeeded for swift-syntax $version"
            
            if [ "${{ inputs.run-tests }}" = "true" ] && [ -d "Tests" ]; then
              echo "Running tests with swift-syntax $version"
              if swift test -v; then
                echo "Tests passed for swift-syntax $version"
              else
                echo "Tests failed for swift-syntax $version"
                exit 1
              fi
            elif [ "${{ inputs.run-tests }}" = "true" ]; then
              echo "Tests were requested, but no Tests directory found"
            else
              echo "Skipping tests as per configuration"
            fi
          else
            echo "Build failed for swift-syntax $version"
            exit 1
          fi
          
          echo "Compatibility check complete for swift-syntax $version"
          echo "---------------------------------------------------"
        done
        
        echo "All compatibility checks completed successfully"
