name: 'Swift Macro Compatibility Check'

description: 'Builds and optionally tests a Swift package with macros using all relevant swift-syntax versions'

inputs:
  run-tests:
    description: 'Whether to run tests (true/false)'
    required: false
    default: 'false'

  major-versions-only:
    description: 'Whether to test only against major versions (true/false)'
    required: false
    default: 'false'

  verbose:
    description: 'Whether to use verbose output for Swift commands (true/false)'
    required: false
    default: 'false'
    
runs:
  using: "composite"
  steps:
    - name: Check Swift package compatibility
      shell: bash
      run: |
        # Check compatibility of Swift package with multiple swift-syntax versions
        
        # List of all swift-syntax versions
        ALL_VERSIONS=(
          "509.0.0"
          "509.0.1"
          "509.0.2"
          "509.1.0"
          "509.1.1"
          "510.0.0"
          "510.0.1"
          "510.0.2"
          "510.0.3"
          # Temporary solution since swift package resolve {package} --version 600.0.0-prerelease does not work
          "600.0.0-prerelease-2024-08-14"
        )
        
        # List of major swift-syntax versions
        MAJOR_VERSIONS=(
          "509.0.0"
          "510.0.0"
        )
        
        # Choose which versions to use based on input
        if [ "${{ inputs.major-versions-only }}" = "true" ]; then
          VERSIONS=("${MAJOR_VERSIONS[@]}")
        else
          VERSIONS=("${ALL_VERSIONS[@]}")
        fi
        
        # Set verbosity flag
        VERBOSE_FLAG=""
        if [ "${{ inputs.verbose }}" = "true" ]; then
          VERBOSE_FLAG="-v"
        fi

        swift package resolve
        
        for version in "${VERSIONS[@]}"; do
          echo "Testing compatibility with swift-syntax version $version"
                    
          swift package resolve swift-syntax --version $version
          
          echo "Building package with swift-syntax $version"
          if swift build $VERBOSE_FLAG; then
            echo "Build succeeded for swift-syntax $version"
            
            if [ "${{ inputs.run-tests }}" = "true" ]; then
              echo "Running tests with swift-syntax $version"
              if swift test $VERBOSE_FLAG; then
                echo "Tests passed for swift-syntax $version"
              else
                echo "Tests failed for swift-syntax $version"
                exit 1
              fi
            else
              echo "Skipping tests as per configuration"
            fi
          else
            echo "Build failed for swift-syntax $version"
            exit 1
          fi
          
          echo "Compatibility check complete for swift-syntax $version"
          echo "---------------------------------------------------"
        done
        
        echo "All compatibility checks completed successfully"

branding:
  icon: 'check-circle'
  color: 'green'
