name: 'Swift Macro Compatibility Check'

description: 'Builds and optionally tests a Swift package with macros using all relevant swift-syntax versions'

inputs:
  run-tests:
    description: 'Whether to run tests (true/false)'
    required: false
    default: 'false'

  major-versions-only:
    description: 'Whether to test only against major versions (true/false)'
    required: false
    default: 'false'

  verbose:
    description: 'Whether to use verbose output for Swift commands (true/false)'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Run Swift Macro Compatibility Check Script
      shell: bash
      run: |
        # Pass input values to the script
        ARGS=""
        if [ "${{ inputs.run-tests }}" = "true" ]; then
          ARGS="$ARGS --run-tests"
        fi
        if [ "${{ inputs.major-versions-only }}" = "true" ]; then
          ARGS="$ARGS --major-versions-only"
        fi
        if [ "${{ inputs.verbose }}" = "true" ]; then
          ARGS="$ARGS --verbose"
        fi

        # Execute the external script with the arguments
        bash ${{ github.action_path }}/swift-macro-compatibility-check.sh $ARGS

branding:
  icon: 'check-circle'
  color: 'green'