name: Swift Macro Compatibility Check
description: Builds and tests a Swift package with macros using all relevant swift-syntax versions

runs:
  using: "composite"
  steps:
    - name: Check Swift package compatibility
      shell: bash
      run: |
        # List of all relevant swift-syntax versions to test against
        VERSIONS=("509.0.0" "510.0.0")
        
        for version in "${VERSIONS[@]}"; do
          echo "Testing compatibility with swift-syntax version $version"
          
          # Resolve dependencies
          swift package resolve
          swift package resolve swift-syntax --version $version
          
          echo "Building package with swift-syntax $version"
          if swift build -v; then
            echo "Build succeeded for swift-syntax $version"
            
            if [ -d "Tests" ]; then
              echo "Running tests with swift-syntax $version"
              if swift test -v; then
                echo "Tests passed for swift-syntax $version"
              else
                echo "Tests failed for swift-syntax $version"
                exit 1
              fi
            else
              echo "No tests found"
            fi
          else
            echo "Build failed for swift-syntax $version"
            exit 1
          fi
          
          echo "Compatibility check complete for swift-syntax $version"
          echo "---------------------------------------------------"
        done
        
        echo "All compatibility checks completed successfully"
