name: Swift Macro Compatibility Check
description: Builds a Swift package with macros using a specific swift-syntax versions

inputs:
  swift-syntax-version:
    description: swift-syntax versions to test against
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Resolve dependencies
      shell: bash
      run: |
        swift package resolve
        swift package resolve swift-syntax --version ${{ inputs.swift-syntax-version }}

    - name: Build package
      shell: bash
      run: swift build -v

    - name: Run tests
      shell: bash
      run: |
        if [ -d "Tests" ]; then
          swift test -v
        else
          echo "No tests found"
        fi
